### PR TITLE
Vendor assets

### PR DESCRIPTION
**Pull request by Legogris**
Once again thanks for putting this out, I hope you're open to PRs :)

To avoid unnecessary outbound network requests, bundle static assets instead of using CDN. Also adds integrity checksums for js. I'm thinking this should be preferred for a secret-sharing service.

### CODE REVIEW

**Comment by eranchetz** [comment]
@Legogris let me test this locally and I'll merge this asap

**Comment by Shaltz** [comment]
@eranchetz 
Hi, quite interesting PR, 
any ETA in mind ?

**Comment by eranchetz** [comment]
@Shaltz have you been able to test this branch locally? unfortunately I haven't had the time yet, if you have please let us know. 
Thanks

**Comment by Legogris** [comment]
FWIW been running this for month or so with chromium and firefox.

**Comment by Shaltz** [comment]
I'll give it a try asap...
Having heavily modified the HTML for my use, it's a bit tricky for me...
I'll give it a try anyways as soon as I have a minute for myself ;)

**Pull request merged**
