### PR TITLE
Let's Encrypt HTTPS Orchestration, Vendorize

### PR DESCRIPTION
**Pull request by chiefy**
* [live running example](https://secrets.bourbon.stream/)

### CODE REVIEW

**Comment by Haroenv** [comment]
I get "server responded with status of 400" when trying your example

**Comment by chiefy** [comment]
@Haroenv locally? logs?

**Comment by Haroenv** [comment]
```html
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.13.5</center>
</body>
</html>
```

that's for `https://secrets.bourbon.stream/secret` when pressing the button

**Comment by chiefy** [comment]
@Haroenv weird - https://secrets.bourbon.stream/getmsg?token=ce8a1621-be78-0c68-7fe5-547f9aa70d86

**Comment by chiefy** [comment]
@Haroenv I actually think I see the `400` are you on safari? If so, what version can can you do a `uname -a` in terminal?

**Comment by chiefy** [comment]
@Haroenv looks like a javascript error in Safari

**Comment by Haroenv** [comment]
I was using Safari TP 42 (newest) 🤔

**Comment by chiefy** [comment]
@Haroenv don't know what to tell you, that's beta software, use a standard browser and it will work.

**Comment by Haroenv** [comment]
Yep, tried it on different browsers and it works now. Sorry for the confusion

**Comment by eranchetz** [comment]
@chiefy thanks a lot for the contribution! sorry for the late merge :)

**Pull request merged**
